import Providers from "@/lib/providers";
import type { Metadata } from "next";
import { PT_Serif } from "next/font/google";

const font = PT_Serif({
  variable: "--font-serif",
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable} ${font.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
