import Providers from "@/lib/providers";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const font = localFont({
  src: [
    {
      path: "./fonts/times-new-roman.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/times-new-roman-bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/times-new-roman-bold-Italic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${font.variable} ${font.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
